import { Inter } from 'next/font/google';
import Head from 'next/head';
import Header from '../components/Header';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </>
  );
};

export default RootLayout;
